package growwapi

import (
	"fmt"
	"net/url"
	"strconv"
	"time"
)

// https://groww.in/trade-api/docs/curl/orders

// PlaceOrderRequest represents the request data for placing order
// https://groww.in/trade-api/docs/curl/orders#request-schema
type PlaceOrderRequest struct {
	// Trading Symbol of the instrument as defined by the exchange
	TradingSymbol string `json:"trading_symbol"`
	// Quantity of the instrument to order
	Quantity int `json:"quantity"`
	// [Optional] Price of the instrument in rupees case of Limit order
	Price float32 `json:"price,omitempty"`
	// [Optional] Trigger price in rupees for the order
	TriggerPrice float32 `json:"trigger_price,omitempty"`
	// Validity of the order
	Validity Validity `json:"validity"`
	// Stock exchange
	Exchange Exchange `json:"exchange"`
	// Segment of the instrument such as CASH, FNO etc.
	Segment Segment `json:"segment"`
	// Product type
	Product Product `json:"product"`
	// Order type
	OrderType OrderType `json:"order_type"`
	// Transaction type
	TransactionType TransactionType `json:"transaction_type"`
	// User provided 8 to 20 length alphanumeric string with at most two hyphens(-).
	OrderReferenceId string `json:"order_reference_id"`
}

// PlaceOrderResponse represents the response for PlaceOrder
// https://groww.in/trade-api/docs/curl/orders#response-schema
type PlaceOrderResponse struct {
	// Order id generated by Groww for an order
	GrowwOrderId string `json:"groww_order_id"`
	// Current Status of the placed order
	OrderStatus OrderStatus `json:"order_status"`
	// User provided reference id to track the status of an order
	OrderReferenceId string `json:"order_reference_id"`
	// Remark for the order
	Remark string `json:"remark"`
}

// PlaceOrder : This API is used to place a new order in the market.
// https://groww.in/trade-api/docs/curl/orders#place-order
func (c *Client) PlaceOrder(req PlaceOrderRequest) (PlaceOrderResponse, error) {
	const destination = "https://api.groww.in/v1/order/create"
	return doPostRequest[PlaceOrderResponse](c, destination, req)
}

// ModifyOrderRequest represents the request data to modify order
// https://groww.in/trade-api/docs/curl/orders#request-schema-1
type ModifyOrderRequest struct {
	// Quantity of the instrument to order
	Quantity int `json:"quantity"`
	// Price of the instrument in rupees case of Limit order
	Price float32 `json:"price"`
	// Trigger price in rupees for the order
	TriggerPrice float32 `json:"trigger_price"`
	// Order Type
	OrderType OrderType `json:"order_type"`
	// Segment of the instrument such as CASH, FNO etc.
	Segment Segment `json:"segment"`
	// Order id generated by Groww for an order
	GrowwOrderId string `json:"groww_order_id"`
}

// ModifyOrderResponse represents the response data from ModifyOrder
// https://groww.in/trade-api/docs/curl/orders#response-schema-1
type ModifyOrderResponse struct {
	// Order id generated by Groww for an order
	GrowwOrderId string `json:"groww_order_id"`
	// Current status of the placed order
	OrderStatus OrderStatus `json:"order_status"`
}

// ModifyOrder : All pending and open orders can be modified using this API.
// https://groww.in/trade-api/docs/curl/orders#modify-order
func (c *Client) ModifyOrder(req ModifyOrderRequest) (ModifyOrderResponse, error) {
	const destination = "https://api.groww.in/v1/order/modify"
	return doPostRequest[ModifyOrderResponse](c, destination, req)
}

// CancelOrderRequest represents the request data to cancel order
// https://groww.in/trade-api/docs/curl/orders#request-schema-2
type CancelOrderRequest struct {
	// Segment of the instrument such as CASH, FNO etc..
	Segment Segment `json:"segment"`
	// Order id generated by Groww for an order
	GrowwOrderId string `json:"groww_order_id"`
}

// CancelOrderResponse represents the response data from CancelOrder
// https://groww.in/trade-api/docs/curl/orders#response-schema-2
type CancelOrderResponse struct {
	// Order id generated by Groww for an order
	GrowwOrderId string `json:"groww_order_id"`
	// Current status of the placed order
	OrderStatus OrderStatus `json:"order_status"`
}

// CancelOrder : All pending and open orders can be cancelled using this API.
// https://groww.in/trade-api/docs/curl/orders#cancel-order
func (c *Client) CancelOrder(req CancelOrderRequest) (CancelOrderResponse, error) {
	const destination = "https://api.groww.in/v1/order/cancel"
	return doPostRequest[CancelOrderResponse](c, destination, req)
}

// TradeForOrderRequest represents the request data to get trades for order request
// https://groww.in/trade-api/docs/curl/orders#request-schema-3
type TradeForOrderRequest struct {
	// Order id generated by Groww for an order
	GrowwOrderId string
	// Segment of the instrument such as CASH, FNO etc.
	Segment Segment
	// [Optional] Page Number
	Page int
	// [Optional] Size of the page. Maximum size is 50.
	PageSize int
}

// Trade represents the trades for a given order id
// https://groww.in/trade-api/docs/curl/orders#response-schema-3
type Trade struct {
	Price            float32         `json:"price"`
	Isin             string          `json:"isin"`
	Quantity         int             `json:"quantity"`
	GrowwOrderId     string          `json:"groww_order_id"`
	GrowwTradeId     string          `json:"groww_trade_id"`
	ExchangeTradeId  string          `json:"exchange_trade_id"`
	ExchangeOrderId  string          `json:"exchange_order_id"`
	TradeStatus      OrderStatus     `json:"trade_status"`
	TradingSymbol    string          `json:"trading_symbol"`
	Remark           string          `json:"remark"`
	Exchange         Exchange        `json:"exchange"`
	Segment          Segment         `json:"segment"`
	Product          Product         `json:"product"`
	TransactionType  TransactionType `json:"transaction_type"`
	CreatedAt        time.Time       `json:"created_at"`
	TradeDateTime    time.Time       `json:"trade_date_time"`
	SettlementNumber string          `json:"settlement_number"`
}

func (t TradeForOrderRequest) queryParams() url.Values {
	out := make(url.Values)
	out.Add("segment", string(t.Segment))

	if t.Page != 0 {
		out.Add("page", strconv.Itoa(t.Page))
	}

	if t.PageSize != 0 {
		out.Add("page_size", strconv.Itoa(t.PageSize))
	}

	return out
}

// GetTradesForOrder : An order may be executed at the exchange differently from how an order is placed based on market liquidity.
// A single order might get executed in a single fulfilment, or as multiple smaller fulfilments.
// For example, an order of 100 quantity can get executed as 20-50-30 or any other combination.
// Since each of these fulfilments is defined as a trade, an order can be assigned to one or more trades.
// You can use groww_order_id to retrieve all the trades assigned to that order
// https://groww.in/trade-api/docs/curl/orders#get-trades-for-order
func (c *Client) GetTradesForOrder(req TradeForOrderRequest) ([]Trade, error) {
	destination := fmt.Sprintf("https://api.groww.in/v1/order/trades/%s", req.GrowwOrderId)
	return doGetRequest[[]Trade](c, destination, req)
}

type orderStatusRequest interface {
	url() string
	asQueryParam
}

// OrderStatusRequestWithGrowwOrderId represents the request to get order status given the GrowwOrderId
// https://groww.in/trade-api/docs/curl/orders#request-schema-4
type OrderStatusRequestWithGrowwOrderId struct {
	// Order id generated by Groww for an order
	GrowwOrderId string
	// Segment of the instrument such as CASH, FNO etc.
	Segment Segment
}

// OrderStatusRequestWithOrderReferenceId represents the request to get order status given the OrderReferenceId
// https://groww.in/trade-api/docs/curl/orders#request-schema-5
type OrderStatusRequestWithOrderReferenceId struct {
	// User provided reference id to track the status of an order
	OrderReferenceId string
	// Segment of the instrument such as CASH, FNO etc.
	Segment Segment
}

// OrderStatusResponse represents the order status response received from Groww
// https://groww.in/trade-api/docs/curl/orders#response-4
type OrderStatusResponse struct {
	GrowwOrderId     string `json:"groww_order_id"`
	OrderStatus      string `json:"order_status"`
	Remark           string `json:"remark"`
	FilledQuantity   int    `json:"filled_quantity"`
	OrderReferenceId string `json:"order_reference_id"`
}

func (o OrderStatusRequestWithGrowwOrderId) queryParams() url.Values {
	out := make(url.Values)
	out.Add("segment", string(o.Segment))
	return out
}

func (o OrderStatusRequestWithGrowwOrderId) url() string {
	return fmt.Sprintf("https://api.groww.in/v1/order/status/%s", o.GrowwOrderId)
}

func (o OrderStatusRequestWithOrderReferenceId) queryParams() url.Values {
	out := make(url.Values)
	out.Add("segment", string(o.Segment))
	return out
}

func (o OrderStatusRequestWithOrderReferenceId) url() string {
	return fmt.Sprintf("https://api.groww.in/v1/order/status/reference/%s", o.OrderReferenceId)
}

// GetOrderStatus The API can be used to check the status of an order using the GrowwOrderId or OrderReferenceId.
// Use OrderStatusRequestWithGrowwOrderId or OrderStatusRequestWithOrderReferenceId
// https://groww.in/trade-api/docs/curl/orders#get-order-status
func (c *Client) GetOrderStatus(req orderStatusRequest) (OrderStatusResponse, error) {
	destination := req.url()
	return doGetRequest[OrderStatusResponse](c, destination, req)
}

// Order represents an order in Groww
// https://groww.in/trade-api/docs/curl/orders#response-schema-7
type Order struct {
	// Order id generated by Groww for an order
	GrowwOrderId string `json:"groww_order_id"`
	// Groww specific trading symbol of the instrument
	TradingSymbol string `json:"trading_symbol"`
	// Status of the placed order
	OrderStatus OrderStatus `json:"order_status"`
	// Remark for the order
	Remark string `json:"remark"`
	// Quantity of the instrument to order
	Quantity int `json:"quantity"`
	// Price of the instrument in rupees case of Limit order
	Price float32 `json:"price"`
	// Trigger price in rupees for the order
	TriggerPrice float32 `json:"trigger_price"`
	// Quantity of the order which has been executed.
	FilledQuantity int `json:"filled_quantity"`
	// Quantity remained to be filled
	RemainingQuantity int `json:"remaining_quantity"`
	// Avg price of the order placed
	AverageFillPrice float32 `json:"average_fill_price"`
	// Deliverable quantity
	DeliverableQuantity int `json:"deliverable_quantity"`
	// Status of the order placed after market (Not applicable during market hours)
	AmoStatus AfterMarketOrderStatus `json:"amo_status"`
	// Validity of the order
	Validity Validity `json:"validity"`
	// Stock Exchange
	Exchange Exchange `json:"exchange"`
	// Order Type
	OrderType OrderType `json:"order_type"`
	// Transaction type of the trade
	TransactionType TransactionType `json:"transaction_type"`
	// Segment of the instrument such as CASH, FNO etc.
	Segment Segment `json:"segment"`
	// Product type
	Product Product `json:"product"`
	// Order created at date and time
	CreatedAt time.Time `json:"created_at"`
	// Date and Time at which order was placed at exchange
	ExchangeTime time.Time `json:"exchange_time"`
	// Date on which trade has taken place
	TradeDate time.Time `json:"trade_date"`
	// User provided reference id to track the status of an order
	OrderReferenceId string `json:"order_reference_id"`
}

// ListOrdersRequest represent the request for Listing Orders
// https://groww.in/trade-api/docs/curl/orders#request-schema-6
type ListOrdersRequest struct {
	Segment  Segment
	Page     int
	PageSize int
}

func (l ListOrdersRequest) queryParams() url.Values {
	out := make(url.Values)

	if l.Segment != "" {
		out.Add("segment", string(l.Segment))
	}

	if l.Page != 0 {
		out.Add("page", strconv.Itoa(l.Page))
	}

	if l.PageSize != 0 {
		out.Add("page_size", strconv.Itoa(l.PageSize))
	}

	return out
}

// ListOrders : The API can be used to get the history of orders executed for the day.
// It includes all the orders for the day including open, pending, and executed ones.
// https://groww.in/trade-api/docs/curl/orders#get-order-list
func (c *Client) ListOrders(req ListOrdersRequest) ([]Order, error) {
	destination := "https://api.groww.in/v1/order/list"
	return doGetRequest[[]Order](c, destination, req)
}

// GetOrderDetailsRequest represents the request to get order details
type GetOrderDetailsRequest struct {
	// Order id generated by Groww for an order
	GrowwOrderId string
	// Segment of the instrument such as CASH, FNO etc.
	Segment Segment
}

func (g GetOrderDetailsRequest) queryParams() url.Values {
	out := make(url.Values)
	out.Add("segment", string(g.Segment))
	return out
}

// GetOrderDetails : The api can be used to get the details of an order using the GrowwOrderId.
// https://groww.in/trade-api/docs/curl/orders#get-order-details
func (c *Client) GetOrderDetails(req GetOrderDetailsRequest) (Order, error) {
	destination := fmt.Sprintf(" https://api.groww.in/v1/order/detail/%s", req.GrowwOrderId)
	return doGetRequest[Order](c, destination, req)
}
